//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
<<<<<<< HEAD:CHS.TLC.Data.NM.Web/CHS.TLC.Data.NM.Web/Models/InternationalBank.cs
        public int InternationalBankId { get; set; }
        public string Description { get; set; }
        public string State { get; set; }
=======
        public Bank()
        {
            this.Supplier = new HashSet<Supplier>();
        }
    
        public int BankId { get; set; }
        public string Description { get; set; }
        public string State { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Supplier> Supplier { get; set; }
>>>>>>> 57d2163f53fbd8daa250e31d80afb12de6273d18:CHS.TLC.Data.NM.Web/CHS.TLC.Data.NM.Web/Models/Bank.cs
    }
}
