//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.BankContact = new HashSet<BankContact>();
        }
    
        public int BankId { get; set; }
        public string Description { get; set; }
        public string State { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<BankContact> BankContact { get; set; }
    }
}
