//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankContact
    {
        public int BankContactId { get; set; }
        public int ContactId { get; set; }
        public int BankId { get; set; }
        public string AccountSoles { get; set; }
        public string AccountDollars { get; set; }
        public string State { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
