//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.BankContact = new HashSet<BankContact>();
        }
    
        public int BankId { get; set; }
        public string Description { get; set; }
        public string State { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<BankContact> BankContact { get; set; }
    }
}
