//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.PrePurcherseOrder = new HashSet<PrePurcherseOrder>();
            this.Supplier = new HashSet<Supplier>();
        }
    
        public int CountryId { get; set; }
        public string Name { get; set; }
        public string State { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<PrePurcherseOrder> PrePurcherseOrder { get; set; }
        public virtual ICollection<Supplier> Supplier { get; set; }
    }
}
