//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.EntryNote = new HashSet<EntryNote>();
            this.OutputNote = new HashSet<OutputNote>();
        }
    
        public int DocumentId { get; set; }
        public int DocumentTypeId { get; set; }
        public string State { get; set; }
        public string DocumentNumber { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual ICollection<EntryNote> EntryNote { get; set; }
        public virtual ICollection<OutputNote> OutputNote { get; set; }
    }
}
