//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryNote
    {
        public int EntryNoteId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Code { get; set; }
        public string State { get; set; }
        public int MovementTypeId { get; set; }
        public string SupplierGuideNumber { get; set; }
        public string TransportGuideNumber { get; set; }
        public string Seal { get; set; }
        public System.TimeSpan TransportTime { get; set; }
        public int DestinationStoreId { get; set; }
        public int TransferStoreId { get; set; }
        public int SupplierId { get; set; }
        public int DocumentId { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Store Store { get; set; }
        public virtual MovementType MovementType { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Store Store1 { get; set; }
    }
}
