//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incoterms
    {
        public Incoterms()
        {
            this.PurcherseOrder = new HashSet<PurcherseOrder>();
        }
    
        public int IncotermsId { get; set; }
        public string Name { get; set; }
        public string Acronym { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<PurcherseOrder> PurcherseOrder { get; set; }
    }
}
