//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TLCDataNMEntities : DbContext
    {
        public TLCDataNMEntities()
            : base("name=TLCDataNMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bank> Bank { get; set; }
        public DbSet<Document> Document { get; set; }
        public DbSet<DocumentType> DocumentType { get; set; }
        public DbSet<EntryNote> EntryNote { get; set; }
        public DbSet<Family> Family { get; set; }
        public DbSet<MeasureUnit> MeasureUnit { get; set; }
        public DbSet<MovementType> MovementType { get; set; }
        public DbSet<Option> Option { get; set; }
        public DbSet<OutputNote> OutputNote { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<RoleOption> RoleOption { get; set; }
        public DbSet<Store> Store { get; set; }
        public DbSet<SubFamily> SubFamily { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
        public DbSet<TaxPercentage> TaxPercentage { get; set; }
        public DbSet<TypeExistence> TypeExistence { get; set; }
    }
}
