//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TLCDataNMEntities : DbContext
    {
        public TLCDataNMEntities()
            : base("name=TLCDataNMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bank> Bank { get; set; }
        public DbSet<BankContact> BankContact { get; set; }
        public DbSet<Contact> Contact { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<Currency> Currency { get; set; }
        public DbSet<DocumentType> DocumentType { get; set; }
        public DbSet<EntryNote> EntryNote { get; set; }
        public DbSet<Family> Family { get; set; }
        public DbSet<Incoterms> Incoterms { get; set; }
        public DbSet<Item> Item { get; set; }
        public DbSet<MeasureUnit> MeasureUnit { get; set; }
        public DbSet<MovementType> MovementType { get; set; }
        public DbSet<Option> Option { get; set; }
        public DbSet<OutputNote> OutputNote { get; set; }
        public DbSet<Password> Password { get; set; }
        public DbSet<Port> Port { get; set; }
        public DbSet<PrePurcherseOrder> PrePurcherseOrder { get; set; }
        public DbSet<PrePurcherseOrderDetail> PrePurcherseOrderDetail { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<PurcherseOrder> PurcherseOrder { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<RoleOption> RoleOption { get; set; }
        public DbSet<StockProduct> StockProduct { get; set; }
        public DbSet<StockProductDetail> StockProductDetail { get; set; }
        public DbSet<Store> Store { get; set; }
        public DbSet<SubFamily> SubFamily { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
        public DbSet<TaxPercentage> TaxPercentage { get; set; }
        public DbSet<Tolerance> Tolerance { get; set; }
        public DbSet<Treasury> Treasury { get; set; }
        public DbSet<TypeExistence> TypeExistence { get; set; }
        public DbSet<User> User { get; set; }
    }
}
