//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementType
    {
        public MovementType()
        {
            this.EntryNote = new HashSet<EntryNote>();
            this.OutputNote = new HashSet<OutputNote>();
        }
    
        public int MovementTypeId { get; set; }
        public string Name { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<EntryNote> EntryNote { get; set; }
        public virtual ICollection<OutputNote> OutputNote { get; set; }
    }
}
