//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputNote
    {
        public OutputNote()
        {
            this.StockProductDetail = new HashSet<StockProductDetail>();
        }
    
        public int OutputNoteId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Code { get; set; }
        public int MovementTypeId { get; set; }
        public int DestinationStoreId { get; set; }
        public int OriginalStoreId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public string Other { get; set; }
        public bool IsOfficeGuide { get; set; }
        public bool IsTransferGuide { get; set; }
        public string State { get; set; }
        public string DocumentCode { get; set; }
    
        public virtual MovementType MovementType { get; set; }
        public virtual Store Store { get; set; }
        public virtual Store Store1 { get; set; }
        public virtual ICollection<StockProductDetail> StockProductDetail { get; set; }
    }
}
