//------------------------------------------------------------------------------
// <auto-generated>
<<<<<<< HEAD
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
=======
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
>>>>>>> 57d2163f53fbd8daa250e31d80afb12de6273d18
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputNote
    {
        public int OutputNoteId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Code { get; set; }
        public int MovementTypeId { get; set; }
        public int DestinationStoreId { get; set; }
        public int OriginalStoreId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public string Other { get; set; }
        public bool IsOfficeGuide { get; set; }
        public bool IsTransferGuide { get; set; }
        public string State { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual MovementType MovementType { get; set; }
        public virtual Store Store { get; set; }
        public virtual Store Store1 { get; set; }
    }
}
