//------------------------------------------------------------------------------
// <auto-generated>
<<<<<<< HEAD
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
=======
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
>>>>>>> 3e14766d94afd9d479fb0f42e1d946b6bf182a4f
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Password
    {
        public int PasswordId { get; set; }
        public string State { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> BlockDate { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
