//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrePurcherseOrderDetail
    {
        public int PrePurcherseOrderDetailId { get; set; }
        public int PrePurcherseOrderId { get; set; }
        public decimal Quantity { get; set; }
        public int MeasureUnitId { get; set; }
        public int ProductId { get; set; }
        public string State { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual MeasureUnit MeasureUnit { get; set; }
        public virtual PrePurcherseOrder PrePurcherseOrder { get; set; }
        public virtual Product Product { get; set; }
    }
}
