//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.PrePurcherseOrderDetail = new HashSet<PrePurcherseOrderDetail>();
            this.StockProduct = new HashSet<StockProduct>();
        }
    
        public int ProductId { get; set; }
        public int SubFamilyId { get; set; }
        public int TypeExistenceId { get; set; }
        public Nullable<int> MeasureUnitPrimaryId { get; set; }
        public Nullable<int> MeasureUnitSecondaryId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string InternalCode { get; set; }
        public bool IsActive { get; set; }
        public string Barcode { get; set; }
        public string Color { get; set; }
        public string InvoiceDescription { get; set; }
        public string LocalDescription { get; set; }
        public string LotNumberPurchase { get; set; }
        public int TaxPercentageAdvalorenId { get; set; }
        public int TaxPercentageAffectionIGVId { get; set; }
        public int TaxPercentagePerceptionId { get; set; }
        public int TaxPercentageDetractionId { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<bool> IsPurchase { get; set; }
        public string OtherMeasureUnit { get; set; }
        public string ConversionFactor { get; set; }
        public Nullable<int> MinimumStock { get; set; }
        public string MinimumLot { get; set; }
        public string State { get; set; }
    
        public virtual MeasureUnit MeasureUnit { get; set; }
        public virtual MeasureUnit MeasureUnit1 { get; set; }
        public virtual ICollection<PrePurcherseOrderDetail> PrePurcherseOrderDetail { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual SubFamily SubFamily { get; set; }
        public virtual TaxPercentage TaxPercentage { get; set; }
        public virtual TaxPercentage TaxPercentage1 { get; set; }
        public virtual TaxPercentage TaxPercentage2 { get; set; }
        public virtual TaxPercentage TaxPercentage3 { get; set; }
        public virtual TypeExistence TypeExistence { get; set; }
        public virtual ICollection<StockProduct> StockProduct { get; set; }
    }
}
