//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.RoleOption = new HashSet<RoleOption>();
            this.User = new HashSet<User>();
        }
    
        public int RoleId { get; set; }
        public string Name { get; set; }
        public string Acronym { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<RoleOption> RoleOption { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
