//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockProduct
    {
        public StockProduct()
        {
            this.StockProductDetail = new HashSet<StockProductDetail>();
        }
    
        public int StockProductId { get; set; }
        public int ProductId { get; set; }
        public decimal Quantity { get; set; }
        public string State { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<StockProductDetail> StockProductDetail { get; set; }
    }
}
