//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockProduct
    {
        public StockProduct()
        {
            this.StockProductDetail = new HashSet<StockProductDetail>();
        }
    
        public int StockProductId { get; set; }
        public int ProductId { get; set; }
        public decimal Quantity { get; set; }
        public string State { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<StockProductDetail> StockProductDetail { get; set; }
    }
}
