//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockProductDetail
    {
        public int StockProductDetailId { get; set; }
        public int StockProductId { get; set; }
        public string State { get; set; }
        public string Operation { get; set; }
        public decimal Value { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> EntryNoteId { get; set; }
        public Nullable<int> OutputNoteId { get; set; }
    
        public virtual EntryNote EntryNote { get; set; }
        public virtual OutputNote OutputNote { get; set; }
        public virtual StockProduct StockProduct { get; set; }
    }
}
