//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.EntryNote = new HashSet<EntryNote>();
            this.EntryNote1 = new HashSet<EntryNote>();
            this.OutputNote = new HashSet<OutputNote>();
            this.OutputNote1 = new HashSet<OutputNote>();
        }
    
        public int StoreId { get; set; }
        public string Name { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<EntryNote> EntryNote { get; set; }
        public virtual ICollection<EntryNote> EntryNote1 { get; set; }
        public virtual ICollection<OutputNote> OutputNote { get; set; }
        public virtual ICollection<OutputNote> OutputNote1 { get; set; }
    }
}
