//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubFamily
    {
        public SubFamily()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int SubFamilyId { get; set; }
        public int FamilyId { get; set; }
        public string Description { get; set; }
        public string State { get; set; }
    
        public virtual Family Family { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
