//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.EntryNote = new HashSet<EntryNote>();
            this.Product = new HashSet<Product>();
        }
    
        public int SupplierId { get; set; }
        public Nullable<int> BankId { get; set; }
        public string RUC { get; set; }
        public string BussinessName { get; set; }
        public string Provenance { get; set; }
        public string Origin { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string FirstContactName { get; set; }
        public string FirstContactLastName { get; set; }
        public string FirstContactCharge { get; set; }
        public string FirstContactEmail { get; set; }
        public string SecondContactName { get; set; }
        public string SecondContactLastName { get; set; }
        public string SecondContactCharge { get; set; }
        public string SecondContactEmail { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual ICollection<EntryNote> EntryNote { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
