//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHS.TLC.Data.NM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxPercentage
    {
        public TaxPercentage()
        {
            this.Product = new HashSet<Product>();
            this.Product1 = new HashSet<Product>();
            this.Product2 = new HashSet<Product>();
            this.Product3 = new HashSet<Product>();
        }
    
        public int TaxPercentageId { get; set; }
        public decimal Description { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<Product> Product1 { get; set; }
        public virtual ICollection<Product> Product2 { get; set; }
        public virtual ICollection<Product> Product3 { get; set; }
    }
}
